# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

exclude: [ _locale , _scripts , "*.backup", "*.bak" ]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true

# Setup
baseurl: "/jekyll-plurlingva-dok"
auxtoro: Jean Michault
