# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
baseurl:          ""
auxtoro: Jean Michault

exclude: [ _locale , _scripts , "*.backup", "*.bak" ]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
